export enum TableActions {
  DISABLED_GET_ROW_MENU = 'DISABLED_GET_ROW_MENU',
  HISTORY_GET_ROW_MENU = 'HISTORY_GET_ROW_MENU',
  INFO = 'INFO',
  COPY = 'COPY',
  DELETE = 'DELETE',
  UPDATE = 'UPDATE',
  SELECT = 'SELECT', // cái này chưa có
  COLLAPSE = 'COLLAPSE',
  DISABLED_ALL_ACTIONS = 'DISABLED_ALL_ACTIONS',
  DISABLED_ROW = 'DISABLED_ROW',
  DISABLED_CHECKBOX = 'DISABLED_CHECKBOX',
}

export enum TableRowKey {
  TOTAL = 'TOTAL',
  TOTAL_INCOME = 'TOTAL_INCOME',
}
