FROM node:lts-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .

ARG SSO_FE_PORT_MAP
ARG SSO_FE_URL
ARG SSO_BE_URL
ARG OFFICE_BE_URL
ARG SERVER_BUILD

ARG FIREBASE_PROJECT_ID
ARG FIREBASE_VAPID_KEY
ARG FIREBASE_API_KEY
ARG FIREBASE_AUTH_DOMAIN
ARG FIREBASE_STORAGE_BUCKET
ARG FIREBASE_MESSAGING_SENDER_ID
ARG FIREBASE_APP_ID


ENV PORT=$SSO_FE_PORT_MAP
ENV REACT_APP_URL=$SSO_FE_URL
ENV REACT_APP_BE_URL=$SSO_BE_URL
ENV REACT_APP_BE_OFFICE_URL=$OFFICE_BE_URL
ENV REACT_APP_SERVER_BUILD=$SERVER_BUILD

ENV REACT_APP_FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
ENV REACT_APP_FIREBASE_VAPID_KEY=$FIREBASE_VAPID_KEY
ENV REACT_APP_FIREBASE_API_KEY=$FIREBASE_API_KEY
ENV REACT_APP_FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
ENV REACT_APP_FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET
ENV REACT_APP_FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID
ENV REACT_APP_FIREBASE_APP_ID=$FIREBASE_APP_ID

RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html
COPY .nginx/nginx.conf /etc/nginx/nginx.conf  

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
